@store_name = handingo
@api_key = 7cea0936c288f0043f52941aa6c86026
@access_token = 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

### ?fields=title,vendor,product_type
GET https://{{store_name}}.myshopify.com/admin/api/2023-07/products/6690861023407.json
X-Shopify-Access-Token: {{access_token}}

###

GET https://{{store_name}}.myshopify.com/admin/api/2023-07/products.json?variant_sku=36682
X-Shopify-Access-Token: {{access_token}}

###